apiVersion: v1
kind: ResourceQuota
metadata:
  name: ml-quota
  namespace: ml-credit-risk
spec:
  hard:
    requests.cpu: "3"
    requests.memory: 6Gi
    limits.cpu: "4"
    limits.memory: 7Gi
    pods: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: ml-limits
  namespace: ml-credit-risk
spec:
  limits:
    - default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      type: Container
